version: 2.1
 
orbs:
  android: circleci/android@2.5.0
  app-distribution: tadashi0713/app-distribution@1.2.0

commands:
  install-maestro:
    steps:
      - run:
          name: Install Maestro
          command: |
            curl -Ls "https://get.maestro.mobile.dev" | bash
            echo 'export PATH="$PATH:$HOME/.maestro/bin"' >> $BASH_ENV

  run-maestro:
    steps:
      - run:
          name: Run checks & tests
          command: ./install_apk.sh

jobs:
  deploy:
    docker:
      - image: cimg/android:2024.01
    environment:
      DEPLOY_DIR: deploy
    steps:
      - checkout
      - app-distribution/upload_android:
          path: wiki.apk
      - run-maestro

workflows:
  main:
    jobs:
      - deploy:
          context:
            - mobile
            - app-distribution
